# Generated by Django 4.1.4 on 2022-12-26 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_category_alter_ksiazki_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazki',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.category'),
        ),
    ]
