# Generated by Django 4.1.4 on 2022-12-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_books_rename_opis_category_category_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=60)),
                ('client_surname', models.CharField(max_length=60)),
                ('client_email', models.CharField(max_length=60)),
                ('client_phone', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
            },
        ),
    ]
