# Generated by Django 4.1.4 on 2023-01-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_kategoria_producent_produkty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients_info',
            options={'verbose_name': 'klient', 'verbose_name_plural': 'klienci'},
        ),
    ]
