# Generated by Django 4.1.4 on 2022-12-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Clients_info',
        ),
    ]
