# Generated by Django 4.1.4 on 2023-01-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_alter_clients_info_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients_info',
            old_name='client_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='clients_info',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='clients_info',
            old_name='client_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='clients_info',
            old_name='client_surname',
            new_name='surname',
        ),
    ]
